services:
  nginx:
    image: nginx:alpine
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - app

  app:
    build: .
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6969/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    command:
      - /app/GenZ
      - --app-host
      - "0.0.0.0"
      - --app-port
      - "6969"
      - --db-host
      - db
      - --db-port
      - "5432"
      - --db-user
      - ${DB_USER}
      - --db-password
      - ${DB_PASSWORD}
      - --db-database
      - ${DB_DATABASE}

  db:
    image: postgres:18
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
